# -*- coding: utf-8 -*-
"""MERGE_DATA_SET.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qfSfPDTiu3o-ljB87379Iw-S5hDJtHpi
"""

import pandas as pd
from google.colab import files

print("Upload the 4 CSV files:")
uploaded = files.upload()

file_names = list(uploaded.keys())

if len(file_names) != 4:
    raise ValueError("Please upload exactly 4 CSV files.")

def prepare_file(file):
    raw = pd.read_csv(file, header=None)

    location_row = raw[
        raw.apply(
            lambda row: row.astype(str).str.contains("latitude", case=False, na=False).any(),
            axis=1
        )
    ]

    if location_row.empty:
        raise ValueError(f"Latitude information not found in {file}")

    location_index = location_row.index[0]

    latitude = pd.to_numeric(raw.iloc[location_index + 1, 0], errors="coerce")
    longitude = pd.to_numeric(raw.iloc[location_index + 1, 1], errors="coerce")

    header_row = raw[
        raw.apply(
            lambda row: row.astype(str).str.contains("time", case=False, na=False).any(),
            axis=1
        )
    ]

    if header_row.empty:
        raise ValueError(f"Time header not found in {file}")

    header_index = header_row.index[0]

    data = raw.iloc[header_index + 1:].copy()

    data = data.iloc[:, :2]

    data.columns = ["time", "value"]

    data["time"] = pd.to_datetime(data["time"], errors="coerce")

    data["value"] = pd.to_numeric(data["value"], errors="coerce")

    data = data.dropna(subset=["time"])

    data["latitude"] = latitude
    data["longitude"] = longitude

    return data[["time", "latitude", "longitude", "value"]]


humidity = prepare_file(file_names[0])
rainfall = prepare_file(file_names[1])
temperature = prepare_file(file_names[2])
wind_speed = prepare_file(file_names[3])

humidity = humidity.rename(columns={"value": "Humidity_pct"})
rainfall = rainfall.rename(columns={"value": "Rainfall_mm"})
temperature = temperature.rename(columns={"value": "Temp_C"})
wind_speed = wind_speed.rename(columns={"value": "Windspeed_kmh"})

merged_df = pd.merge(
    humidity,
    rainfall,
    on=["time", "latitude", "longitude"],
    how="outer"
)

merged_df = pd.merge(
    merged_df,
    temperature,
    on=["time", "latitude", "longitude"],
    how="outer"
)

merged_df = pd.merge(
    merged_df,
    wind_speed,
    on=["time", "latitude", "longitude"],
    how="outer"
)

merged_df = merged_df.rename(
    columns={
        "time": "Date",
        "latitude": "Lat",
        "longitude": "Long"
    }
)

merged_df = merged_df[
    [
        "Date",
        "Rainfall_mm",
        "Humidity_pct",
        "Temp_C",
        "Windspeed_kmh",
        "Lat",
        "Long"
    ]
]

merged_df = merged_df.drop_duplicates()

merged_df = merged_df.sort_values("Date")

merged_df = merged_df.reset_index(drop=True)

print("\n======================================")
print("4 WEATHER DATASETS MERGED SUCCESSFULLY")
print("======================================")

print("\nMerged Dataset Shape:")
print(merged_df.shape)

print("\nMerged Columns:")
print(merged_df.columns.tolist())

print("\nMerged Dataset:")
print(merged_df.head(10))

output_file = "MERGED_WEATHER_DATASET.csv"

merged_df.to_csv(output_file, index=False)

print("\nOutput file:", output_file)

files.download(output_file)

import pandas as pd
import numpy as np
import os
from google.colab import files


# ============================================================
# 1. UPLOAD EXACTLY 5 DISASTER DATASETS
# ============================================================

print("====================================================")
print("UPLOAD EXACTLY 5 DISASTER DATASETS")
print("====================================================")
print("1. Cyclone")
print("2. Floods")
print("3. Forest Fire")
print("4. Earthquake")
print("5. Landslide")
print("====================================================")

uploaded = files.upload()

file_names = list(uploaded.keys())

if len(file_names) != 5:
    raise ValueError(
        f"You uploaded {len(file_names)} files. "
        "Please upload exactly 5 datasets."
    )

print("\nUploaded files:")
for file in file_names:
    print("-", file)


# ============================================================
# 2. READ CSV / EXCEL AUTOMATICALLY
# ============================================================

def read_dataset(file):

    extension = os.path.splitext(file)[1].lower()

    if extension == ".csv":

        try:
            df = pd.read_csv(
                file,
                low_memory=False
            )

        except UnicodeDecodeError:

            df = pd.read_csv(
                file,
                encoding="latin1",
                low_memory=False
            )

    elif extension in [".xlsx", ".xls"]:

        df = pd.read_excel(file)

    else:

        raise ValueError(
            f"Unsupported file format: {extension}"
        )

    return df


# ============================================================
# 3. CLEAN COLUMN NAMES
# ============================================================

def clean_columns(df):

    df.columns = (
        df.columns
        .astype(str)
        .str.strip()
        .str.replace("\ufeff", "", regex=False)
        .str.replace("<br>", " ", regex=False)
        .str.replace("\n", " ", regex=False)
        .str.replace(r"\s+", " ", regex=True)
    )

    return df


# ============================================================
# 4. FIND COLUMN AUTOMATICALLY
# ============================================================

def find_column(df, possible_names):

    # Exact match
    for name in possible_names:

        if name in df.columns:
            return name

    # Case-insensitive match
    column_map = {
        str(col).strip().lower(): col
        for col in df.columns
    }

    for name in possible_names:

        if name.lower() in column_map:
            return column_map[name.lower()]

    return None


# ============================================================
# 5. EXTRACT NUMERIC VALUES
# ============================================================

def extract_number(series):

    return pd.to_numeric(
        series
        .astype(str)
        .str.extract(
            r"([-+]?\d*\.?\d+)"
        )[0],
        errors="coerce"
    )


# ============================================================
# 6. INDIA FILTER
# ============================================================
#
# Approximate geographical limits of India:
#
# Latitude  : 6.5  to 37.5
# Longitude : 68.0 to 97.5
#
# Records outside these limits are removed.
# ============================================================

def filter_india(df):

    df = df.copy()

    df["Lat"] = pd.to_numeric(
        df["Lat"],
        errors="coerce"
    )

    df["Long"] = pd.to_numeric(
        df["Long"],
        errors="coerce"
    )

    # Remove missing coordinates
    df = df.dropna(
        subset=[
            "Lat",
            "Long"
        ]
    )

    india_mask = (
        (df["Lat"] >= 6.5) &
        (df["Lat"] <= 37.5) &
        (df["Long"] >= 68.0) &
        (df["Long"] <= 97.5)
    )

    df = df[india_mask].copy()

    return df


# ============================================================
# 7. PROCESS CYCLONE
# ============================================================

def process_cyclone(file):

    print("\n====================================================")
    print("PROCESSING CYCLONE")
    print("====================================================")

    df = read_dataset(file)
    df = clean_columns(df)

    print("File:", file)
    print("Original records:", len(df))

    lat_col = find_column(
        df,
        [
            "LAT",
            "Lat",
            "Latitude",
            "latitude"
        ]
    )

    long_col = find_column(
        df,
        [
            "LON",
            "Lon",
            "Long",
            "Longitude",
            "longitude"
        ]
    )

    # Prefer wind speed as cyclone magnitude
    mag_col = find_column(
        df,
        [
            "USA_WIND",
            "WMO_WIND",
            "NEWDELHI_WIND",
            "BOM_WIND",
            "TOKYO_WIND"
        ]
    )

    if lat_col is None:
        raise ValueError(
            f"Latitude column not found in {file}"
        )

    if long_col is None:
        raise ValueError(
            f"Longitude column not found in {file}"
        )

    result = pd.DataFrame()

    result["Event_id"] = [
        "CY-" + str(i + 1)
        for i in range(len(df))
    ]

    result["Disaster_type"] = "Cyclone"

    result["Lat"] = extract_number(
        df[lat_col]
    )

    result["Long"] = extract_number(
        df[long_col]
    )

    if mag_col is not None:

        result["Magnitude"] = extract_number(
            df[mag_col]
        )

    else:

        result["Magnitude"] = np.nan

    # Cyclone severity
    result["Severity"] = np.select(
        [
            result["Magnitude"] >= 118,
            result["Magnitude"] >= 89,
            result["Magnitude"] >= 62
        ],
        [
            "High",
            "Medium",
            "Low"
        ],
        default="Low"
    )

    # India only
    result = filter_india(result)

    print("India records:", len(result))

    return result[
        [
            "Event_id",
            "Disaster_type",
            "Lat",
            "Long",
            "Magnitude",
            "Severity"
        ]
    ]


# ============================================================
# 8. PROCESS EARTHQUAKE
# ============================================================

def process_earthquake(file):

    print("\n====================================================")
    print("PROCESSING EARTHQUAKE")
    print("====================================================")

    df = read_dataset(file)
    df = clean_columns(df)

    print("File:", file)
    print("Original records:", len(df))

    lat_col = find_column(
        df,
        [
            "Lat",
            "LAT",
            "Latitude",
            "latitude"
        ]
    )

    long_col = find_column(
        df,
        [
            "Long",
            "LON",
            "Lon",
            "Longitude",
            "longitude"
        ]
    )

    mag_col = find_column(
        df,
        [
            "Magnitude",
            "magnitude",
            "MAG"
        ]
    )

    if lat_col is None:
        raise ValueError(
            f"Latitude column not found in {file}"
        )

    if long_col is None:
        raise ValueError(
            f"Longitude column not found in {file}"
        )

    result = pd.DataFrame()

    result["Event_id"] = [
        "EQ-" + str(i + 1)
        for i in range(len(df))
    ]

    result["Disaster_type"] = "Earthquake"

    result["Lat"] = extract_number(
        df[lat_col]
    )

    result["Long"] = extract_number(
        df[long_col]
    )

    if mag_col is not None:

        result["Magnitude"] = extract_number(
            df[mag_col]
        )

    else:

        result["Magnitude"] = np.nan

    # Earthquake severity
    result["Severity"] = np.select(
        [
            result["Magnitude"] >= 6.0,
            result["Magnitude"] >= 5.0,
            result["Magnitude"] >= 4.0
        ],
        [
            "High",
            "Medium",
            "Low"
        ],
        default="Low"
    )

    # India only
    result = filter_india(result)

    print("India records:", len(result))

    return result[
        [
            "Event_id",
            "Disaster_type",
            "Lat",
            "Long",
            "Magnitude",
            "Severity"
        ]
    ]


# ============================================================
# 9. PROCESS FOREST FIRE
# ============================================================

def process_forest_fire(file):

    print("\n====================================================")
    print("PROCESSING FOREST FIRE")
    print("====================================================")

    df = read_dataset(file)
    df = clean_columns(df)

    print("File:", file)
    print("Original records:", len(df))

    lat_col = find_column(
        df,
        [
            "Lat",
            "LAT",
            "Latitude",
            "latitude"
        ]
    )

    long_col = find_column(
        df,
        [
            "Lon",
            "LON",
            "Long",
            "Longitude",
            "longitude"
        ]
    )

    if lat_col is None:
        raise ValueError(
            f"Latitude column not found in {file}"
        )

    if long_col is None:
        raise ValueError(
            f"Longitude column not found in {file}"
        )

    result = pd.DataFrame()

    result["Event_id"] = [
        "FF-" + str(i + 1)
        for i in range(len(df))
    ]

    result["Disaster_type"] = "Forest Fire"

    result["Lat"] = extract_number(
        df[lat_col]
    )

    result["Long"] = extract_number(
        df[long_col]
    )

    # Forest fire does not necessarily have magnitude
    result["Magnitude"] = np.nan

    severity_col = find_column(
        df,
        [
            "Severity",
            "severity",
            "Fire Severity",
            "Fire_Severity",
            "Intensity",
            "Fire Intensity"
        ]
    )

    if severity_col is not None:

        result["Severity"] = (
            df[severity_col]
            .astype(str)
            .str.strip()
        )

    else:

        result["Severity"] = "Unknown"

    # India only
    result = filter_india(result)

    print("India records:", len(result))

    return result[
        [
            "Event_id",
            "Disaster_type",
            "Lat",
            "Long",
            "Magnitude",
            "Severity"
        ]
    ]


# ============================================================
# 10. PROCESS FLOOD
# ============================================================

def process_flood(file):

    print("\n====================================================")
    print("PROCESSING FLOOD")
    print("====================================================")

    df = read_dataset(file)
    df = clean_columns(df)

    print("File:", file)
    print("Original records:", len(df))

    lat_col = find_column(
        df,
        [
            "Lat",
            "LAT",
            "Latitude",
            "latitude"
        ]
    )

    long_col = find_column(
        df,
        [
            "Long",
            "LON",
            "Lon",
            "Longitude",
            "longitude"
        ]
    )

    if lat_col is None:
        raise ValueError(
            f"Latitude column not found in {file}"
        )

    if long_col is None:
        raise ValueError(
            f"Longitude column not found in {file}"
        )

    result = pd.DataFrame()

    result["Event_id"] = [
        "FL-" + str(i + 1)
        for i in range(len(df))
    ]

    result["Disaster_type"] = "Flood"

    result["Lat"] = extract_number(
        df[lat_col]
    )

    result["Long"] = extract_number(
        df[long_col]
    )

    # Look for magnitude/intensity type column
    mag_col = find_column(
        df,
        [
            "Magnitude",
            "magnitude",
            "Water Level",
            "water_level",
            "Intensity",
            "intensity"
        ]
    )

    if mag_col is not None:

        result["Magnitude"] = extract_number(
            df[mag_col]
        )

    else:

        result["Magnitude"] = np.nan

    severity_col = find_column(
        df,
        [
            "Severity",
            "severity",
            "Severity Level",
            "Impact",
            "Risk Level"
        ]
    )

    if severity_col is not None:

        result["Severity"] = (
            df[severity_col]
            .astype(str)
            .str.strip()
        )

    else:

        result["Severity"] = "Unknown"

    # India only
    result = filter_india(result)

    print("India records:", len(result))

    return result[
        [
            "Event_id",
            "Disaster_type",
            "Lat",
            "Long",
            "Magnitude",
            "Severity"
        ]
    ]


# ============================================================
# 11. PROCESS LANDSLIDE
# ============================================================

def process_landslide(file):

    print("\n====================================================")
    print("PROCESSING LANDSLIDE")
    print("====================================================")

    df = read_dataset(file)
    df = clean_columns(df)

    print("File:", file)
    print("Original records:", len(df))

    lat_col = find_column(
        df,
        [
            "Latitude",
            "latitude",
            "Lat",
            "LAT"
        ]
    )

    long_col = find_column(
        df,
        [
            "Longitude",
            "longitude",
            "Long",
            "Lon",
            "LON"
        ]
    )

    if lat_col is None:
        raise ValueError(
            f"Latitude column not found in {file}"
        )

    if long_col is None:
        raise ValueError(
            f"Longitude column not found in {file}"
        )

    result = pd.DataFrame()

    result["Event_id"] = [
        "LS-" + str(i + 1)
        for i in range(len(df))
    ]

    result["Disaster_type"] = "Landslide"

    result["Lat"] = extract_number(
        df[lat_col]
    )

    result["Long"] = extract_number(
        df[long_col]
    )

    result["Magnitude"] = np.nan

    severity_col = find_column(
        df,
        [
            "Severity",
            "severity",
            "Severity Level",
            "Impact",
            "Intensity"
        ]
    )

    if severity_col is not None:

        result["Severity"] = (
            df[severity_col]
            .astype(str)
            .str.strip()
        )

    else:

        result["Severity"] = "Unknown"

    # India only
    result = filter_india(result)

    print("India records:", len(result))

    return result[
        [
            "Event_id",
            "Disaster_type",
            "Lat",
            "Long",
            "Magnitude",
            "Severity"
        ]
    ]


# ============================================================
# 12. IDENTIFY FILES BY THEIR NAMES
# ============================================================

def find_file(keyword):

    for file in file_names:

        if keyword.lower() in file.lower():
            return file

    return None


cyclone_file = find_file("cyclone")
flood_file = find_file("flood")
forest_fire_file = find_file("forestfire")
earthquake_file = find_file("earthquake")
landslide_file = find_file("landslide")


# ============================================================
# 13. CHECK FILE IDENTIFICATION
# ============================================================

print("\n====================================================")
print("FILE IDENTIFICATION")
print("====================================================")

print("Cyclone      :", cyclone_file)
print("Flood        :", flood_file)
print("Forest Fire  :", forest_fire_file)
print("Earthquake   :", earthquake_file)
print("Landslide    :", landslide_file)


# ============================================================
# 14. MAKE SURE ALL 5 ARE FOUND
# ============================================================

if cyclone_file is None:
    raise ValueError("Cyclone dataset not found.")

if flood_file is None:
    raise ValueError("Flood dataset not found.")

if forest_fire_file is None:
    raise ValueError("Forest Fire dataset not found.")

if earthquake_file is None:
    raise ValueError("Earthquake dataset not found.")

if landslide_file is None:
    raise ValueError("Landslide dataset not found.")


# ============================================================
# 15. PROCESS ALL 5 DATASETS
# ============================================================

all_data = []


# CYCLONE
cyclone_df = process_cyclone(
    cyclone_file
)

all_data.append(cyclone_df)


# FLOOD
flood_df = process_flood(
    flood_file
)

all_data.append(flood_df)


# FOREST FIRE
forest_fire_df = process_forest_fire(
    forest_fire_file
)

all_data.append(forest_fire_df)


# EARTHQUAKE
earthquake_df = process_earthquake(
    earthquake_file
)

all_data.append(earthquake_df)


# LANDSLIDE
landslide_df = process_landslide(
    landslide_file
)

all_data.append(landslide_df)


# ============================================================
# 16. MERGE ALL 5 DATASETS
# ============================================================

print("\n====================================================")
print("MERGING ALL 5 DATASETS")
print("====================================================")

merged_df = pd.concat(
    all_data,
    ignore_index=True
)


# ============================================================
# 17. REMOVE DUPLICATES
# ============================================================

merged_df = merged_df.drop_duplicates()


# ============================================================
# 18. REMOVE INVALID COORDINATES
# ============================================================

merged_df = merged_df.dropna(
    subset=[
        "Lat",
        "Long"
    ]
)


# ============================================================
# 19. FINAL INDIA-ONLY FILTER
# ============================================================

merged_df = filter_india(
    merged_df
)


# ============================================================
# 20. RESET EVENT IDs
# ============================================================

merged_df = merged_df.reset_index(
    drop=True
)

merged_df["Event_id"] = [
    "EVENT-" + str(i + 1)
    for i in range(len(merged_df))
]


# ============================================================
# 21. CLEAN MAGNITUDE
# ============================================================

merged_df["Magnitude"] = pd.to_numeric(
    merged_df["Magnitude"],
    errors="coerce"
)


# ============================================================
# 22. CLEAN SEVERITY
# ============================================================

merged_df["Severity"] = (
    merged_df["Severity"]
    .astype(str)
    .str.strip()
)

merged_df["Severity"] = (
    merged_df["Severity"]
    .replace(
        [
            "",
            "nan",
            "NaN",
            "NA",
            "N/A",
            "None"
        ],
        "Unknown"
    )
)


# ============================================================
# 23. FINAL COLUMN ORDER
# ============================================================

merged_df = merged_df[
    [
        "Event_id",
        "Disaster_type",
        "Lat",
        "Long",
        "Magnitude",
        "Severity"
    ]
]


# ============================================================
# 24. SORT DATASET
# ============================================================

merged_df = merged_df.sort_values(
    by="Disaster_type"
)

merged_df = merged_df.reset_index(
    drop=True
)


# ============================================================
# 25. FINAL OUTPUT
# ============================================================

print("\n====================================================")
print("FINAL INDIA DISASTER DATASET")
print("====================================================")

print("\nFinal Shape:")
print(merged_df.shape)

print("\nFinal Columns:")
print(
    merged_df.columns.tolist()
)

print("\nDisaster Counts:")
print(
    merged_df["Disaster_type"]
    .value_counts()
)

print("\nFirst 20 Records:")
print(
    merged_df.head(20)
)


# ============================================================
# 26. SAVE FINAL CSV
# ============================================================

output_file = "INDIA_MERGED_5_DISASTER_DATASET.csv"

merged_df.to_csv(
    output_file,
    index=False
)


print("\n====================================================")
print("PREPROCESSING COMPLETED SUCCESSFULLY")
print("====================================================")

print("Output file:", output_file)

print(
    "Total India disaster records:",
    len(merged_df)
)


# ============================================================
# 27. DOWNLOAD FINAL CSV
# ============================================================

files.download(
    output_file
)

import pandas as pd
from google.colab import files

# ==========================================
# STEP 1: UPLOAD BOTH CSV FILES
# ==========================================

uploaded = files.upload()

print("\nUploaded files:")
for file in uploaded.keys():
    print("-", file)


# ==========================================
# STEP 2: IDENTIFY HOSPITAL AND SCHOOL FILES
# ==========================================

hospital_file = None
school_file = None

for file in uploaded.keys():

    df_temp = pd.read_csv(file, low_memory=False)

    columns = [str(col).strip().lower() for col in df_temp.columns]

    # Hospital dataset identification
    if "hos_count" in columns or "@lat" in columns:
        hospital_file = file

    # School dataset identification
    elif "tags.amenity" in columns or "tags.name" in columns:
        school_file = file


print("\nHospital file:", hospital_file)
print("School file:", school_file)


# ==========================================
# STEP 3: READ DATASETS
# ==========================================

hospital_df = pd.read_csv(hospital_file, low_memory=False)
school_df = pd.read_csv(school_file, low_memory=False)


# ==========================================
# STEP 4: CLEAN COLUMN NAMES
# ==========================================

hospital_df.columns = hospital_df.columns.astype(str).str.strip()
school_df.columns = school_df.columns.astype(str).str.strip()


# ==========================================
# STEP 5: SELECT REQUIRED HOSPITAL COLUMNS
# ==========================================

hospital = hospital_df[[
    "@id",
    "@lat",
    "@lon",
    "HOS_COUNT"
]].copy()

hospital = hospital.rename(columns={
    "@id": "ID",
    "@lat": "Lat",
    "@lon": "Long",
    "HOS_COUNT": "Hospital_Count"
})

hospital["Type"] = "Hospital"


# ==========================================
# STEP 6: SELECT REQUIRED SCHOOL COLUMNS
# ==========================================

school = school_df[[
    "type",
    "id",
    "lat",
    "lon",
    "tags.amenity",
    "tags.name"
]].copy()

school = school.rename(columns={
    "type": "OSM_Type",
    "id": "ID",
    "lat": "Lat",
    "lon": "Long",
    "tags.amenity": "Amenity",
    "tags.name": "School_Name"
})

school["Type"] = "School"


# ==========================================
# STEP 7: ADD MISSING COLUMNS
# ==========================================

hospital["School_Name"] = None
hospital["Amenity"] = None
hospital["OSM_Type"] = None

school["Hospital_Count"] = 0


# ==========================================
# STEP 8: MAKE SAME COLUMN ORDER
# ==========================================

hospital = hospital[[
    "ID",
    "Lat",
    "Long",
    "Type",
    "Hospital_Count",
    "School_Name",
    "Amenity",
    "OSM_Type"
]]

school = school[[
    "ID",
    "Lat",
    "Long",
    "Type",
    "Hospital_Count",
    "School_Name",
    "Amenity",
    "OSM_Type"
]]


# ==========================================
# STEP 9: MERGE / COMBINE BOTH DATASETS
# ==========================================

merged_df = pd.concat(
    [hospital, school],
    ignore_index=True
)


# ==========================================
# STEP 10: CLEAN DATA
# ==========================================

merged_df["Lat"] = pd.to_numeric(
    merged_df["Lat"],
    errors="coerce"
)

merged_df["Long"] = pd.to_numeric(
    merged_df["Long"],
    errors="coerce"
)

merged_df["Hospital_Count"] = pd.to_numeric(
    merged_df["Hospital_Count"],
    errors="coerce"
).fillna(0)


# Remove rows without coordinates
merged_df = merged_df.dropna(
    subset=["Lat", "Long"]
)


# Remove duplicate rows
merged_df = merged_df.drop_duplicates()


# Reset index
merged_df = merged_df.reset_index(drop=True)


# ==========================================
# STEP 11: DISPLAY RESULT
# ==========================================

print("\n========================================")
print("MERGED DATASET")
print("========================================")

print("Total rows:", len(merged_df))
print("Total columns:", len(merged_df.columns))

display(merged_df.head(10))


# ==========================================
# STEP 12: SAVE AS CSV
# ==========================================

output_file = "HOSPITAL_SCHOOL_MERGED.csv"

merged_df.to_csv(
    output_file,
    index=False
)

print("\nSaved successfully as:", output_file)


# ==========================================
# STEP 13: DOWNLOAD
# ==========================================

files.download(output_file)